---

name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install flake8
        run: pip install flake8

      - name: Lint
        run: flake8 --show-source --statistics --count ./

  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install mypy
        run: pip install mypy

      - name: Check typing
        run: mypy --strict ./
